---
- name: Add unit file for PUMA
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: Reload PUMA
- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/gryaznovart186/db_config
    owner: gryaznovart186
    group: gryaznovart186
- name: Enable PUMA Service
  systemd:
    name: puma
    enabled: yes
    daemon_reload: yes