- name: Configure Reddit
  gather_facts: no
  become: true
  hosts: app
  vars:
    db_host: 10.132.0.63
  tasks:
    - name: Add unit file for PUMA
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: Reload PUMA
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/gryaznovart186/reddit/db_config
        owner: gryaznovart186
        group: gryaznovart186
    - name: Enable PUMA Service
      systemd:
        name: puma
        enabled: yes
        daemon_reload: yes
  handlers:
    - name: Reload PUMA
      systemd:
        name: puma
        state: restarted
