- name: Deploy Reddit
  gather_facts: no
  become: true
  hosts: app
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/gryaznovart186/reddit
        version: monolith
      notify: Reload PUMA
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/gryaznovart186/reddit
  handlers:
    - name: Reload PUMA
      systemd:
        name: puma
        state: restarted
